apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-us-west-site-01-w102
  namespace: wind-turbine-demo
data:
  SITE_NAME:"us-west-offshore-site-01"
  TURBINE_NAME:"turbine-w102"
  TURBINE_INFO:"123"
  WEBSOCKET_URL:"ws://192.168.71.130:30004/ws"