apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-ui
  namespace: wind-turbine-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-ui
  template:
    metadata:
      labels:
        app: frontend-ui
    spec:
      containers:
      - name: frontend-ui
        image: kmikholap/wt-frontend-ui:v8
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: SITE_NAME
          valueFrom:
            configMapKeyRef:
              name: frontend-config-us-west-offshore-site-01
              key: SITE_NAME
        - name: TURBINE_INFO
          valueFrom:
            configMapKeyRef:
              name: frontend-config-us-west-offshore-site-01
              key: TURBINE_INFO
        - name: WEBSOCKET_URL
          valueFrom:
            configMapKeyRef:
              name: frontend-config-us-west-offshore-site-01
              key: WEBSOCKET_URL
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-ui
  namespace: wind-turbine-demo
spec:
  type: NodePort
  selector:
    app: frontend-ui
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 80
    nodePort: 30005