apiVersion: apps/v1
kind: Deployment
metadata:
  name: sensor-simulator
  namespace: wind-turbine-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sensor-simulator
  template:
    metadata:
      labels:
        app: sensor-simulator
    spec:
      containers:
      - name: sensor-simulator
        image: kmikholap/wt-sensor-sim:latest

