apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-api
  namespace: wind-turbine-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-api
  template:
    metadata:
      labels:
        app: backend-api
    spec:
      containers:
      - name: backend-api
        image: kmikholap/wt-backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - name: INFLUXDB_URL
          value: "http://influxdb:8086"
        - name: INFLUXDB_TOKEN
          value: "wttoken"
        - name: INFLUXDB_ORG
          value: "wt-co"
        - name: INFLUXDB_BUCKET
          value: "wind_turbine"
        - name: SITE_NAME
          valueFrom:
            configMapKeyRef:
              name: backend-config-us-west-offshore-site-01
              key: SITE_NAME
        - name: TURBINE_NAME
          valueFrom:
            configMapKeyRef:
              name: backend-config-us-west-offshore-site-01
              key: TURBINE_NAME
        - name: TURBINE_INFO
          valueFrom:
            configMapKeyRef:
              name: backend-config-us-west-offshore-site-01
              key: TURBINE_INFO
        - name: WEBSOCKET_URL
          valueFrom:
            configMapKeyRef:
              name: backend-config-us-west-offshore-site-01
              key: WEBSOCKET_URL
---
apiVersion: v1
kind: Service
metadata:
  name: backend-api
  namespace: wind-turbine-demo
spec:
  selector:
    app: backend-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
    nodePort: 30004
  type: NodePort
